import os

#Run all the plotting scripts
print("This may take several minutes")

# Plot Extracted data and fit (fig 7 and 8)
filename = ("2024-04-15_3-point_efficiency_1sccm_recalib/"
            + "2024-04-15_excess_power_recalib.py")
print(f"Running {filename}")
os.system(f"python {filename}")

# Plot primary extraction
filename = ("2023-04-21_1sccm_15A_TC_z-scan"
            +"_jf_wire_extract_recalib_just_plot.py")
print(f"Running {filename}")
os.system(f"python {filename}")

# Plot simulated heat flow
filename = ("Tschersich_shape_2024-04-17_paper_fBB_heatshield.py")
print(f"Running {filename}")
os.system(f"python {filename}")

# Plot Calibration
filename = ("calib_analysis.py")
print(f"Running {filename}")
os.system(f"python {filename}")


# Additional plots are generated by 2024_04_24_plot_multi_l_eff.ipynb